### ISSUE TITLE
People with active bookings is 2x Total # active bookings

### ISSUE THREAD

**Issue by hartsick** [codeforamerica/jail-dashboard#52] opened 2016-12-12 18:15 UTC
See current production

Grayson suggests it may be because of missing validations

**Comment by graysonwright** [comment] 2016-12-12 23:59
@jennifermarie reset the production database, and the issue is no longer present. We're not sure what caused the problem, but we suspect that some of the old data generators created non-unique keys or other corrupted data. We aren't able to reproduce this in development.

It's possible that the underlying bug has already been resolved by changes to the data generation scripts. If that's the case, we should monitor the production app for a few days to see if the problem returns. If it does, we should dig in and identify the cause. If not, we can treat the issue as fixed.

i'll take this opportunity to do a quick audit of the app's validations, and test and fix up any missing/broken ones.

**Closed** 2016-12-13 01:39 UTC
Labels: in progress
